name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Get current date for docker versioning
      id: date
      run: echo "::set-output name=now::$(date +'%Y-%m-%dT%H-%M-%S')"          
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: jacobarchambault/wordbank:latest,jacobarchambault/wordbank:${{ steps.date.outputs.now }}
